import { createStarCatalog } from "../src/business/catalog.js";
import { assessAnalysisResultForReconcile, buildReconcileDraft, finalizeReconcileDraft } from "../src/business/reconcile.js";
import { WorkspaceDomainError } from "../src/business/model.js";
import { restoreWorkspaceSnapshot } from "../src/business/snapshot.js";
import type { BrowserAnalysisResultV1 } from "../src/structured/batch-orchestration.js";

function expect(value: unknown, message: string): asserts value { if (!value) throw new Error(message); }
function expectError(action: () => unknown, code: string): void { try { action(); } catch (error) { expect(error instanceof WorkspaceDomainError && error.code === code, `expected ${code}`); return; } throw new Error(`expected ${code}`); }
const catalog = createStarCatalog([{ name: "天府", kind: "主星", aliases: [], displayGroup: null, usageTags: [], rawEffectText: null }, { name: "解神", kind: "辅星", aliases: [], displayGroup: null, usageTags: [], rawEffectText: null }], { "天府别名": "天府" });
function occurrence(id: string, overrides: Record<string, unknown> = {}): any { return { occurrenceId: id, row: 0, column: 0, completeness: "complete", effectiveName: "天府", effectiveLevel: 40, quality: "橙", equippedState: "unknown", reviewRequired: false, ...overrides }; }
function result(overrides: Record<string, unknown> = {}): BrowserAnalysisResultV1 {
  const first = occurrence("occ-a");
  return {
    schemaVersion: 1, task: { taskId: "task-1", accountId: "account-1", baseRevision: 0, status: "completed" }, images: [{ sourceImageId: "image-1", sourceOrder: 1, confirmedPool: { imageId: "image-1", pageType: "main" }, status: "completed", error: null, analysis: { pageClassification: { pageType: "main", reviewRequired: false }, occurrences: [first], experienceOccurrences: [], experienceAggregate: null, inventoryHeader: {}, warnings: [] } as any }], failures: [],
    inventory: { status: "confirmed", currentCount: { value: 1, status: "confirmed", sources: [], reviewReasonCodes: [] }, capacity: { value: 100, status: "confirmed", sources: [], reviewReasonCodes: [] } }, overlap: { confirmedPairs: [], relations: [] }, occurrences: [{ occurrenceId: "occ-a", sourceImageId: "image-1", sourceOrder: 1, kind: "ordinary", occurrence: first }], review: { status: "ready_for_review", reasons: [] }, ...overrides,
  } as BrowserAnalysisResultV1;
}
function draft(source = result()) { return buildReconcileDraft(source, { currentAccountId: "account-1", currentRevision: 0, activeTaskId: "task-1", catalog }); }

expect(assessAnalysisResultForReconcile(result(), "account-1", 0, "task-1").eligible, "matching completed result is eligible");
for (const [change, code] of [[{ task: { ...result().task, status: "partial" } }, "partial_requires_retry"], [{ task: { ...result().task, status: "cancelled" } }, "cancelled_result"], [{ task: { ...result().task, status: "failed" } }, "failed_result"], [{ review: { status: "blocked", reasons: [] } }, "analysis_blocked"], [{ task: { ...result().task, baseRevision: "2x" } }, "invalid_base_revision"], [{ task: { ...result().task, baseRevision: 1 } }, "revision_mismatch"]] as const) expect(assessAnalysisResultForReconcile({ ...result(), ...change } as BrowserAnalysisResultV1, "account-1", 0, "task-1").blockReasonCodes.includes(code as any), `${code} blocks ingest`);
expect(assessAnalysisResultForReconcile(result(), "other", 0, "task-1").blockReasonCodes.includes("account_mismatch"), "wrong account blocks");
expect(assessAnalysisResultForReconcile(result(), "account-1", 0, "other").blockReasonCodes.includes("active_task_mismatch"), "wrong task blocks");

const clean = draft(); expect(clean.status === "ready_to_finalize" && clean.ordinaryGroups.length === 1, "clean complete occurrence forms a group");
let id = 0; const finalized = finalizeReconcileDraft(clean, {}, { catalog, gameVersion: "如鸢", createStarInstanceId: () => `fresh-${++id}` });
expect(finalized.workspace.inventory.length === 1 && finalized.workspace.inventory[0]!.starInstanceId === "fresh-1", "ID is created only at finalize");
expect(String(finalized.workspace.inventory[0]!.starInstanceId) !== "occ-a" && Object.keys(finalized.workspace.planTargets).length === 0 && finalized.workspace.postprocessRevision === 0, "final rebuild has fresh IDs and clears plans");
const persistedOccurrence = finalized.workspace.importReview.occurrences["occ-a"]!;
expect(persistedOccurrence && persistedOccurrence.name === "天府" && persistedOccurrence.level === 40 && persistedOccurrence.quality === "橙" && persistedOccurrence.inventoryAction === "keep" && persistedOccurrence.removedFromCurrentInventory === false && !("rawOcrCandidates" in persistedOccurrence) && !("visualEvidence" in persistedOccurrence) && !("sourceRect" in persistedOccurrence), "finalize persists only lightweight editable occurrence evidence with a fresh current-inventory deletion flag");
const oldWorkspace = JSON.parse(JSON.stringify(finalized.workspace)); delete oldWorkspace.importReview.occurrences;
expect(Object.keys(restoreWorkspaceSnapshot(oldWorkspace, catalog).importReview.occurrences).length === 0, "old workspace snapshots default missing occurrence evidence to an empty record");
const oldOccurrenceWorkspace = JSON.parse(JSON.stringify(finalized.workspace)); delete oldOccurrenceWorkspace.importReview.occurrences["occ-a"].removedFromCurrentInventory;
expect(restoreWorkspaceSnapshot(oldOccurrenceWorkspace, catalog).importReview.occurrences["occ-a"]!.removedFromCurrentInventory === false, "old occurrence snapshots default missing current-inventory deletion flags to false");
const suggestedOnly = draft(result({ images: [{ ...result().images[0]!, confirmedPool: null }] }));
const suggestedOnlyWorkspace = finalizeReconcileDraft(suggestedOnly, {}, { catalog, gameVersion: "如鸢", createStarInstanceId: () => "suggested-only" }).workspace;
expect(suggestedOnlyWorkspace.importReview.imagePools["image-1"] === "main" && !suggestedOnlyWorkspace.importReview.confirmedImagePools.includes("image-1"), "classifier suggestion does not imply a confirmed image pool");
const confirmedSupport = draft(result({ images: [{ ...result().images[0]!, confirmedPool: { imageId: "image-1", pageType: "support" } }] }));
const confirmedSupportWorkspace = finalizeReconcileDraft(confirmedSupport, {}, { catalog, gameVersion: "如鸢", createStarInstanceId: () => "confirmed-support" }).workspace;
expect(confirmedSupportWorkspace.importReview.imagePools["image-1"] === "support" && confirmedSupportWorkspace.importReview.confirmedImagePools.includes("image-1") && (confirmedSupportWorkspace.importReview.imageAudit["image-1"] as any).suggestedPageType === "main", "confirmed pool overrides formal pool while preserving classifier suggestion separately");

const partialOccurrence = occurrence("partial", { completeness: "partial_bottom" }); const partialDraft = draft(result({ occurrences: [{ occurrenceId: "partial", sourceImageId: "image-1", sourceOrder: 1, kind: "ordinary", occurrence: partialOccurrence }], images: [{ ...result().images[0]!, analysis: { ...(result().images[0]!.analysis as any), occurrences: [partialOccurrence] } }] }));
expect(partialDraft.excludedOrdinaryOccurrences.length === 1 && partialDraft.candidates.length === 0, "partial card is retained as excluded audit only");
const partialFinal = finalizeReconcileDraft(partialDraft, {}, { catalog, gameVersion: "如鸢" });
expect(partialFinal.workspace.inventory.length === 0 && partialFinal.workspace.importReview.occurrences.partial!.inventoryAction === "exclude_fragment", "partial occurrence remains as lightweight excluded evidence without entering inventory");

const missing = occurrence("missing", { effectiveName: null, reviewRequired: true }); const missingDraft = draft(result({ occurrences: [{ occurrenceId: "missing", sourceImageId: "image-1", sourceOrder: 1, kind: "ordinary", occurrence: missing }], images: [{ ...result().images[0]!, analysis: { ...(result().images[0]!.analysis as any), occurrences: [missing] } }], review: { status: "needs_review", reasons: [] } }));
expect(missingDraft.ordinaryReviewItems.length === 1 && missingDraft.status === "requires_review", "missing required field is not dropped");
expectError(() => finalizeReconcileDraft(missingDraft, {}, { catalog, gameVersion: "如鸢" }), "reconcile_review_required");
const edited = finalizeReconcileDraft(missingDraft, { ordinary: { missing: { action: "edit", name: "天府别名", level: 40, quality: "橙" } } }, { catalog, gameVersion: "如鸢", createStarInstanceId: () => "edited" });
expect(edited.workspace.inventory[0]!.name === "天府" && edited.workspace.inventory[0]!.manualStatus === "user_resolved" && edited.workspace.inventory[0]!.equippedState === "unknown", "edit normalizes identity fields while retaining the internal equipped state");
const excluded = finalizeReconcileDraft(missingDraft, { ordinary: { missing: { action: "exclude" } } }, { catalog, gameVersion: "如鸢" }); expect(excluded.workspace.inventory.length === 0 && excluded.workspace.importReview.occurrences.missing!.inventoryAction === "exclude_false_box" && !excluded.workspace.importReview.occurrences.missing!.manualOverride, "explicit exclusion stays as non-manual editable evidence");

const b = occurrence("occ-b", { row: 1 }); const c = occurrence("occ-c", { row: 2 }); const duplicateResult = result({ occurrences: ["occ-a", "occ-b", "occ-c"].map((occurrenceId, index) => ({ occurrenceId, sourceImageId: "image-1", sourceOrder: 1, kind: "ordinary", occurrence: [occurrence("occ-a"), b, c][index] })), images: [{ ...result().images[0]!, analysis: { ...(result().images[0]!.analysis as any), occurrences: [occurrence("occ-a"), b, c] } }], overlap: { confirmedPairs: [], relations: [{ relationId: "rel-ab", pairId: "pair", leftOccurrenceId: "occ-a", rightOccurrenceId: "occ-b", status: "duplicate", evidence: {}, reviewReasonCodes: [] }, { relationId: "rel-bc", pairId: "pair", leftOccurrenceId: "occ-b", rightOccurrenceId: "occ-c", status: "duplicate", evidence: {}, reviewReasonCodes: [] }] } });
const duplicateDraft = draft(duplicateResult); expect(duplicateDraft.ordinaryGroups.length === 1 && duplicateDraft.ordinaryGroups[0]!.occurrenceIds.length === 3, "transitive confirmed duplicates form one component");
id = 0; const duplicateFinal = finalizeReconcileDraft(duplicateDraft, {}, { catalog, gameVersion: "如鸢", createStarInstanceId: () => `component-${++id}` }); expect(duplicateFinal.workspace.inventory.length === 1 && (duplicateFinal.workspace.inventory[0]!.provenance.audit as any).duplicateRelationIds.length === 2, "component has one ID and minimal duplicate audit");
const inconsistent = draft({ ...duplicateResult, occurrences: [...duplicateResult.occurrences.slice(0, 2), { ...duplicateResult.occurrences[2]!, occurrence: occurrence("occ-c", { effectiveLevel: 41 }) }], review: { status: "ready_for_review", reasons: [] } }); expect(inconsistent.status === "blocked" && inconsistent.blockReasonCodes.includes("reconcile_duplicate_component_inconsistent"), "inconsistent confirmed component blocks finalize");
const qualityA = occurrence("quality-a", { quality: "橙", qualityConfidence: .2 }); const qualityB = occurrence("quality-b", { quality: "紫", qualityConfidence: .9 });
const qualityResult = result({ occurrences: [qualityA, qualityB].map((item, index) => ({ occurrenceId: item.occurrenceId, sourceImageId: "image-1", sourceOrder: index + 1, kind: "ordinary" as const, occurrence: item })), images: [{ ...result().images[0]!, analysis: { ...(result().images[0]!.analysis as any), occurrences: [qualityA, qualityB] } }], overlap: { confirmedPairs: [], relations: [{ relationId: "quality-duplicate", pairId: "pair", leftOccurrenceId: "quality-a", rightOccurrenceId: "quality-b", status: "duplicate", evidence: {}, reviewReasonCodes: [] }] } });
const qualityDraft = draft(qualityResult); expect(qualityDraft.status === "ready_to_finalize" && qualityDraft.ordinaryGroups.length === 1, "quality disagreement does not split a name-level duplicate component");
expect(finalizeReconcileDraft(qualityDraft, {}, { catalog, gameVersion: "如鸢", createStarInstanceId: () => "quality-auto" }).workspace.inventory[0]!.quality === "紫", "automatic quality conflict chooses the higher-confidence occurrence deterministically");
const manualQualityA = occurrence("manual-quality-a", { quality: "橙", qualityConfidence: .9, reviewRequired: true }); const manualQualityB = occurrence("manual-quality-b", { quality: "紫", qualityConfidence: .1, reviewRequired: true });
const manualQualityResult = result({ occurrences: [manualQualityA, manualQualityB].map((item, index) => ({ occurrenceId: item.occurrenceId, sourceImageId: "image-1", sourceOrder: index + 1, kind: "ordinary" as const, occurrence: item })), images: [{ ...result().images[0]!, analysis: { ...(result().images[0]!.analysis as any), occurrences: [manualQualityA, manualQualityB] } }], overlap: { confirmedPairs: [], relations: [{ relationId: "manual-quality-duplicate", pairId: "pair", leftOccurrenceId: "manual-quality-a", rightOccurrenceId: "manual-quality-b", status: "duplicate", evidence: {}, reviewReasonCodes: [] }] }, review: { status: "needs_review", reasons: [] } });
const manualQualityDraft = draft(manualQualityResult);
expect(finalizeReconcileDraft(manualQualityDraft, { ordinary: { "manual-quality-a": { action: "edit", name: "天府", level: 40, quality: "紫" }, "manual-quality-b": { action: "accept_suggested" } } }, { catalog, gameVersion: "如鸢", createStarInstanceId: () => "quality-manual" }).workspace.inventory[0]!.quality === "紫", "one manual quality edit overrides automatic quality evidence");
expectError(() => finalizeReconcileDraft(manualQualityDraft, { ordinary: { "manual-quality-a": { action: "edit", name: "天府", level: 40, quality: "橙" }, "manual-quality-b": { action: "edit", name: "天府", level: 40, quality: "紫" } } }, { catalog, gameVersion: "如鸢", createStarInstanceId: () => "quality-conflict" }), "reconcile_manual_component_conflict");

const pendingLeft = Array.from({ length: 4 }, (_, column) => occurrence(`left-${column}`, { row: 4, column })); const pendingRight = Array.from({ length: 4 }, (_, column) => occurrence(`right-${column}`, { row: 5, column }));
const pendingRefs = [...pendingLeft, ...pendingRight].map((item, index) => ({ occurrenceId: item.occurrenceId, sourceImageId: index < 4 ? "image-1" : "image-2", sourceOrder: index < 4 ? 1 : 2, kind: "ordinary" as const, occurrence: item }));
const possible = draft(result({ occurrences: pendingRefs, images: [{ ...result().images[0]!, analysis: { ...(result().images[0]!.analysis as any), occurrences: pendingLeft } }, { sourceImageId: "image-2", sourceOrder: 2, status: "completed", error: null, analysis: { pageClassification: { pageType: "main", reviewRequired: false }, occurrences: pendingRight, experienceOccurrences: [], experienceAggregate: null, inventoryHeader: {}, warnings: [] } as any }], overlap: { confirmedPairs: [], relations: pendingLeft.map((item, column) => ({ relationId: `possible-${column}`, pairId: "pair", leftOccurrenceId: item.occurrenceId, rightOccurrenceId: pendingRight[column]!.occurrenceId, status: "possible_duplicate" as const, evidence: {}, reviewReasonCodes: ["overlap_row_requires_review"] })) }, review: { status: "needs_review", reasons: [] } }));
expect(possible.overlapReviewItems.length === 1 && possible.overlapReviewItems[0]!.relationIds.length === 4, "pending overlap is one atomic four-card row review");
expectError(() => finalizeReconcileDraft(possible, {}, { catalog, gameVersion: "如鸢" }), "reconcile_review_required");
const pendingReviewId = possible.overlapReviewItems[0]!.rowReviewId;
expectError(() => finalizeReconcileDraft(possible, { overlap: { "possible-0": { action: "merge" } } }, { catalog, gameVersion: "如鸢" }), "reconcile_review_required");
expect(finalizeReconcileDraft(possible, { overlap: { [pendingReviewId]: { action: "merge" } } }, { catalog, gameVersion: "如鸢", createStarInstanceId: (() => { let n = 0; return () => `merged-${++n}`; })() }).workspace.inventory.length === 4, "row merge resolves all four matching cards together");
expect(finalizeReconcileDraft(possible, { overlap: { [pendingReviewId]: { action: "keep_separate" } } }, { catalog, gameVersion: "如鸢", createStarInstanceId: (() => { let n = 0; return () => `separate-${++n}`; })() }).workspace.inventory.length === 8, "row keep-separate retains all cards together");
const oneSideUnknownRight = pendingRight.map((item, column) => column === 2 ? { ...item, effectiveName: null, reviewRequired: true } : item);
const oneSideUnknownRefs = [...pendingLeft, ...oneSideUnknownRight].map((item, index) => ({ occurrenceId: item.occurrenceId, sourceImageId: index < 4 ? "image-1" : "image-2", sourceOrder: index < 4 ? 1 : 2, kind: "ordinary" as const, occurrence: item }));
const oneSideUnknown = draft(result({ occurrences: oneSideUnknownRefs, images: [{ ...result().images[0]!, analysis: { ...(result().images[0]!.analysis as any), occurrences: pendingLeft } }, { sourceImageId: "image-2", sourceOrder: 2, status: "completed", error: null, analysis: { pageClassification: { pageType: "main", reviewRequired: false }, occurrences: oneSideUnknownRight, experienceOccurrences: [], experienceAggregate: null, inventoryHeader: {}, warnings: [] } as any }], overlap: { confirmedPairs: [], relations: pendingLeft.map((item, column) => ({ relationId: `unknown-merge-${column}`, pairId: "unknown-merge", leftOccurrenceId: item.occurrenceId, rightOccurrenceId: oneSideUnknownRight[column]!.occurrenceId, status: "possible_duplicate" as const, evidence: {}, reviewReasonCodes: ["overlap_row_requires_review"] })) }, review: { status: "needs_review", reasons: [] } }));
const oneSideUnknownReviewId = oneSideUnknown.overlapReviewItems[0]!.rowReviewId;
const oneSideUnknownFinal = finalizeReconcileDraft(oneSideUnknown, { overlap: { [oneSideUnknownReviewId]: { action: "merge" } } }, { catalog, gameVersion: "如鸢", createStarInstanceId: (() => { let n = 0; return () => `unknown-merge-${++n}`; })() });
expect(oneSideUnknownFinal.workspace.inventory.length === 4 && oneSideUnknownFinal.workspace.inventory.some((item) => item.name === "天府" && item.level === 40), "one-side unknown row merge resolves four physical stars from the counterpart evidence without an ordinary resolution");
expect(oneSideUnknownFinal.workspace.importReview.occurrences["right-2"]!.name === null, "one-side unknown merge preserves the source occurrence unknown evidence instead of fabricating OCR");

const experienceSource = result({ images: [{ ...result().images[0]!, analysis: { ...(result().images[0]!.analysis as any), experienceAggregate: { orangeCount: 3, purpleCount: null, whiteCount: null } } }, { sourceImageId: "image-2", sourceOrder: 2, status: "completed", error: null, analysis: { pageClassification: { pageType: "experience", reviewRequired: false }, occurrences: [], experienceOccurrences: [], experienceAggregate: { orangeCount: 3, purpleCount: null, whiteCount: null }, warnings: [] } as any }] });
expect(draft(experienceSource).experience.orange === 3, "repeated experience observations are not summed");
const conflictExperience = draft({ ...experienceSource, images: [{ ...experienceSource.images[0]!, analysis: { ...(experienceSource.images[0]!.analysis as any), experienceAggregate: { orangeCount: 3, purpleCount: null, whiteCount: null } } }, { ...experienceSource.images[1]!, analysis: { ...(experienceSource.images[1]!.analysis as any), experienceAggregate: { orangeCount: 4, purpleCount: null, whiteCount: null } } }] });
expect(conflictExperience.experience.orange === null && conflictExperience.status === "requires_review", "conflicting experience remains reviewable null");
const manualExperience = finalizeReconcileDraft(conflictExperience, { experience: { orange: 9 } }, { catalog, gameVersion: "如鸢", createStarInstanceId: () => "experience-manual" });
expect(manualExperience.workspace.experience.orange === 9 && manualExperience.workspace.experience.manualFields.includes("orange"), "manual experience resolution is retained");
const reviewExperience = draft({ ...experienceSource, images: [{ ...experienceSource.images[0]!, analysis: { ...(experienceSource.images[0]!.analysis as any), experienceOccurrences: [{ occurrenceId: "orange-review", canonicalType: "orange", reviewRequired: true }] } }] });
expectError(() => finalizeReconcileDraft(reviewExperience, {}, { catalog, gameVersion: "如鸢" }), "reconcile_review_required");
expect(finalizeReconcileDraft(reviewExperience, { experience: { orange: 3 } }, { catalog, gameVersion: "如鸢", createStarInstanceId: () => "experience-review" }).workspace.experience.manualFields.includes("orange"), "known review-required experience needs explicit resolution even when aggregates agree");

const bagConflict = draft(result({ inventory: { status: "conflict", currentCount: { value: 101, status: "confirmed", sources: [], reviewReasonCodes: ["current_conflict"] }, capacity: { value: 100, status: "candidate", sources: [], reviewReasonCodes: ["capacity_candidate"] } } }));
expect(bagConflict.bag.currentCount === null && bagConflict.bag.capacity === null, "invalid bag pair is not guessed");
const manualBag = finalizeReconcileDraft(bagConflict, { bag: { currentCount: 5, capacity: 100 } }, { catalog, gameVersion: "如鸢", createStarInstanceId: () => "bag-manual" });
expect(manualBag.workspace.bag.currentCount === 5 && manualBag.workspace.bag.manualFields.join(",") === "capacity,currentCount", "manual bag fields are retained");

const aliasOccurrence = occurrence("alias", { effectiveName: "天府别名" }); const aliasDraft = draft(result({ occurrences: [{ occurrenceId: "alias", sourceImageId: "image-1", sourceOrder: 1, kind: "ordinary", occurrence: aliasOccurrence }], images: [{ ...result().images[0]!, analysis: { ...(result().images[0]!.analysis as any), occurrences: [aliasOccurrence] } }] }));
expect(aliasDraft.candidates[0]!.name === "天府" && aliasDraft.status === "ready_to_finalize", "effective alias is canonicalized before formal candidate creation");
const reviewRequired = occurrence("review", { reviewRequired: true }); const reviewDraft = draft(result({ occurrences: [{ occurrenceId: "review", sourceImageId: "image-1", sourceOrder: 1, kind: "ordinary", occurrence: reviewRequired }], images: [{ ...result().images[0]!, analysis: { ...(result().images[0]!.analysis as any), occurrences: [reviewRequired] } }], review: { status: "needs_review", reasons: [] } }));
expectError(() => finalizeReconcileDraft(reviewDraft, {}, { catalog, gameVersion: "如鸢" }), "reconcile_review_required");
expect(finalizeReconcileDraft(reviewDraft, { ordinary: { review: { action: "accept_suggested" } } }, { catalog, gameVersion: "如鸢", createStarInstanceId: () => "accepted" }).workspace.inventory.length === 1, "reviewRequired requires and permits explicit acceptance");

const unavailable = draft(result({ overlap: { confirmedPairs: [], relations: [{ relationId: "unavailable", pairId: "pair", leftOccurrenceId: null, rightOccurrenceId: null, status: "unavailable", evidence: {}, reviewReasonCodes: ["endpoint_missing"] }] }, review: { status: "needs_review", reasons: [] } }));
expect(unavailable.status !== "blocked" && finalizeReconcileDraft(unavailable, {}, { catalog, gameVersion: "如鸢", createStarInstanceId: () => "unavailable-separate" }).workspace.inventory.length === 1, "unavailable overlap leaves complete evidence separate instead of blocking the whole OCR commit");
const notDuplicate = draft(result({ occurrences: [{ occurrenceId: "occ-a", sourceImageId: "image-1", sourceOrder: 1, kind: "ordinary", occurrence: occurrence("occ-a") }, { occurrenceId: "occ-b", sourceImageId: "image-1", sourceOrder: 1, kind: "ordinary", occurrence: b }], images: [{ ...result().images[0]!, analysis: { ...(result().images[0]!.analysis as any), occurrences: [occurrence("occ-a"), b] } }], overlap: { confirmedPairs: [], relations: [{ relationId: "not", pairId: "pair", leftOccurrenceId: "occ-a", rightOccurrenceId: "occ-b", status: "not_duplicate", evidence: {}, reviewReasonCodes: [] }] } }));
let threeIds = 0; const notDuplicateFinal = finalizeReconcileDraft(notDuplicate, {}, { catalog, gameVersion: "如鸢", createStarInstanceId: () => `not-${++threeIds}` });
expect(notDuplicateFinal.workspace.inventory.length === 2 && new Set(notDuplicateFinal.starInstanceIds).size === 2, "not_duplicate stars remain separate fresh IDs");
expect((notDuplicateFinal.workspace.importReview.overlapAudit[0] as any).status === "not_duplicate", "minimal audit retains all overlap relation statuses");
console.log("Phase 2B reconcile eligibility, draft, resolution, ID, duplicate, bag and experience checks passed");
