import { readFileSync } from 'node:fs';
import assert from 'node:assert/strict';
const source = readFileSync(new URL('../src/product.ts', import.meta.url), 'utf8');
const handoff = readFileSync(new URL('../src/product-ocr-commit-handoff.ts', import.meta.url), 'utf8');
const commit = source.slice(source.indexOf('async function commitOcrDraft('), source.indexOf('async function beginOcrRun('));
assert.match(commit, /commit: \(\) => workspaceController\.commitOcrReconcile/);
assert.match(commit, /retireCommitted\(runContext\.accountId, controllerGeneration\)/);
assert.match(commit, /runContext: null, evidence, persisted: true/);
assert.match(commit, /status: "completed"/);
assert.match(commit, /reviewSaveState = "saved"/);
assert.match(commit, /releaseImages\(importImages\)/);
assert.match(commit, /importImages = \[\]/);
assert.match(commit, /overlapRelations = \[\]/);
assert.doesNotMatch(commit, /\.dispose\(/);
assert.match(source, /reviewRunContext\(options, prior\?\.runContext \?\? null\)/);
const crops = source.slice(source.indexOf('async function preparePendingReviewRowCrops('), source.indexOf('async function commitOcrDraft('));
assert.match(crops, /reviewSourceBlob\(session\.runContext/);
assert.match(crops, /getCurrentImage\(id\)/);
assert.match(crops, /createImageBitmap\(blob\)/);
const viewer = source.slice(source.indexOf('async function openReviewSourceImage('), source.indexOf('function setPreviewImage('));
assert.match(viewer, /getCurrentImage\(id\)/);
assert.match(viewer, /URL\.createObjectURL\(image\.blob\)/);
assert.match(viewer, /openImageViewer\(items, sourceImageId, revocable\)/);
assert.doesNotMatch(handoff, /YuanHub|MaaYuan|CaptureBatch|captureId|transport|onCapture/);
console.log('PASS P5 product wiring: durable boundary, persisted review/crops/viewer, URL ownership and no host/runtime disposal');
